### ISSUE TITLE
Sign up is throwing an error

### ISSUE THREAD

**Issue by cparsons9712** [G4be34/coding-with-callie-todo-app#11]
In the frontend this is the response:
![image](https://github.com/G4be34/coding-with-callie-todo-app/assets/114779120/249398a3-4434-4c8b-a365-de769247a461)

In the backend these are the logs:
![image](https://github.com/G4be34/coding-with-callie-todo-app/assets/114779120/2e2f1dfa-9bdd-440e-a954-3acaad56aceb)

**Comment by G4be34** [comment]
This might've been from previously having incorrect config settings, but should be fixed with PR #12!
